version: "3.8"

services:
  postgresql:
    image: postgres:13.5-bullseye
    container_name: postgres
    environment:
      - POSTGRES_DB=crickinfo
      - POSTGRES_PASSWORD=2811
    ports:
      - 5432:5432
    networks:
      - newnetwork
    volumes:
      - postvol:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  crick_info_app:
    build: .
    container_name: crick_info_container
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/crickinfo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=2811
    networks:
      - newnetwork
    depends_on:
      postgresql:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postvol:

networks:
  newnetwork:
